      MODULE EIRMOD_REFUSR
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      PRIVATE

      PUBLIC :: EIRENE_REFUSR, EIRENE_REFUSR_INIT,
     .          EIRENE_RF2USR,
     .          EIRENE_SPTUSR, EIRENE_SPTUSR_INIT,
     .          EIRENE_DEALLOC_REFUSR

      CONTAINS

      SUBROUTINE EIRENE_REFUSR_INIT
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_REFUSR_INIT

      SUBROUTINE EIRENE_SPTUSR_INIT
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_SPTUSR_INIT

      SUBROUTINE EIRENE_SPTUSR
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_SPTUSR

      SUBROUTINE EIRENE_REFUSR (XMW,XCW,XMP,XCP,IGASF,IGAST,ZCOS,ZSIN,
     .                          EXPI,RPROB,E0TERM,
     .                          ITYP,MSURF,ISPZO,
     .                          IRET)
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: XMW,XCW,XMP,XCP,ZCOS,ZSIN,EXPI,RPROB,
     .                        E0TERM
      INTEGER, INTENT(IN) :: IGASF,IGAST,ITYP,MSURF,ISPZO
      INTEGER, INTENT(OUT) :: IRET
      IRET = 0
      RETURN
      END SUBROUTINE EIRENE_REFUSR

      SUBROUTINE EIRENE_RF2USR (IMOL,MOL_DEFAULT)
      IMPLICIT NONE
      INTEGER, INTENT(INOUT) :: IMOL
      INTEGER, INTENT(IN)    :: MOL_DEFAULT
      IMOL = MOL_DEFAULT
      RETURN
      END SUBROUTINE EIRENE_RF2USR

      SUBROUTINE EIRENE_DEALLOC_REFUSR
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_DEALLOC_REFUSR

      END MODULE EIRMOD_REFUSR
